require 'simplecov'
SimpleCov.coverage_dir 'coverage/cucumber'
SimpleCov.start 'rails' do
  SimpleCov.command_name 'Cucumber'
  add_filter '/spec/'
  add_filter '/features/'
  add_filter '/config/'
  add_filter '/db/'
  add_filter '/vendor/'
  add_filter 'app/jobs/application_job.rb'
  add_filter 'app/mailers/application_mailer.rb'
end

require 'bundler/setup'
# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'factory_bot_rails'
require 'cucumber/rails'
require 'capybara/rspec'
require 'capybara/rspec/matchers'
require 'rspec/expectations'

class CapybaraAppWrapper
  def initialize(app)
    @app = app
  end

  def call(env)
    @app.call(env)
  rescue ActiveRecord::RecordNotFound
    # Only suppress errors for AJAX/XHR requests or specific polling endpoints
    if env['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest' || env['PATH_INFO'] =~ %r{/status$}
      # Return a 404 to the browser instead of crashing the test runner
      [ 404, { 'Content-Type' => 'application/json' }, [ { error: 'Record not found (test cleanup)' }.to_json ] ]
    else
      # If it's a real page load failure, let it crash so we know something is wrong
      raise
    end
  end
end

# Apply the wrapper
Capybara.app = CapybaraAppWrapper.new(Rails.application)

# Reduce log noise
if Rails.env.test?
  ActiveSupport::Notifications.unsubscribe("sql.active_record")
end

OmniAuth.config.test_mode = true

# Add a default mock that can be overridden in step definitions
OmniAuth.config.add_mock(:google_oauth2, {
  provider: 'google_oauth2',
  uid: '123545',
  info: {
    email: 'test@example.com',
    first_name: 'Test',
    last_name: 'User'
  },
  credentials: {
    token: 'mock_token',
    refresh_token: 'mock_refresh_token'
  }
})


World(Capybara::RSpecMatchers)
World(RSpec::Matchers)

# Include FactoryBot in Cucumber World
World(FactoryBot::Syntax::Methods)

# Include Rails route helpers in Cucumber World
World(Rails.application.routes.url_helpers)

# Configure Capybara to use Selenium with headless Chrome for JavaScript tests
Capybara.register_driver :selenium_chrome_headless do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('--headless')
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-dev-shm-usage')
  options.add_argument('--disable-gpu')

  # Ensure clean exit
  options.add_argument('--disable-application-cache')

  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end

Capybara.javascript_driver = :selenium_chrome_headless
# -----------------------------
World(Warden::Test::Helpers)
Warden.test_mode!

After do
  Warden.test_reset!
end

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

# Configure database cleaner for JavaScript scenarios
Before('@javascript') do
  DatabaseCleaner.strategy = :truncation
end

After('@javascript') do
  # Stop any polling before cleanup to reduce race conditions
  begin
    page.execute_script("
      if (window.pollInterval) clearInterval(window.pollInterval);
      if (window.statusPollInterval) clearInterval(window.statusPollInterval);
      // Attempt to stop any other intervals
      var highestIntervalId = setInterval(';');
      for (var i = 0 ; i < highestIntervalId ; i++) {
        clearInterval(i);
      }
    ")
  rescue => e
    # Ignore JavaScript errors during cleanup (e.g. if browser is already closed)
  end

  DatabaseCleaner.clean

  # Give a moment for any final requests to complete
  sleep 0.1
end

# ============================================
# Restaurant Data Setup for Tests
# ============================================

Before do
  # Seed database for tests if empty
  if Restaurant.count == 0
    load Rails.root.join('db', 'seeds.rb')
  end

  # Initialize restaurant service for all scenarios
  @restaurant_service = RestaurantService.new
end

# Warden test helpers for Devise authentication
World(Warden::Test::Helpers)
Warden.test_mode!

After do
  Warden.test_reset!
end

def set_session_for_room(room_id, member_id)
  # This works with Capybara + Selenium
  Capybara.current_session.driver.browser.manage.add_cookie(
    name: "_restaurant_roulette_session",
    value: {
      "member_id_for_room_#{room_id}" => member_id
    }.to_json
  )
end

After('@javascript') do
  # Extra safety cleanup
  page.execute_script("if (window.pollInterval) clearInterval(window.pollInterval);") rescue nil
  DatabaseCleaner.clean
end
