require 'simplecov'
SimpleCov.coverage_dir 'coverage/cucumber'
SimpleCov.start 'rails' do
  SimpleCov.command_name 'Cucumber'
  add_filter '/spec/'
  add_filter '/features/'
  add_filter '/config/'
  add_filter '/db/'
  add_filter '/vendor/'
  add_filter 'app/jobs/application_job.rb'
  add_filter 'app/mailers/application_mailer.rb'
end

require 'bundler/setup'
# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'factory_bot_rails'
require 'cucumber/rails'
require 'capybara/rspec'
require 'capybara/rspec/matchers'
require 'rspec/expectations'

# ============================================
# Enable RSpec Mocks for Cucumber
# ============================================
require 'rspec/mocks'

World(RSpec::Mocks::ExampleMethods)

Before do
  RSpec::Mocks.setup
end

After do
  RSpec::Mocks.verify
  RSpec::Mocks.teardown
end
OmniAuth.config.test_mode = true

# Add a default mock that can be overridden in step definitions
OmniAuth.config.add_mock(:google_oauth2, {
  provider: 'google_oauth2',
  uid: '123545',
  info: {
    email: 'test@example.com',
    first_name: 'Test',
    last_name: 'User'
  },
  credentials: {
    token: 'mock_token',
    refresh_token: 'mock_refresh_token'
  }
})


World(Capybara::RSpecMatchers)
World(RSpec::Matchers)

# Include FactoryBot in Cucumber World
World(FactoryBot::Syntax::Methods)

# Include Rails route helpers in Cucumber World
World(Rails.application.routes.url_helpers)

# Configure Capybara to use Selenium with headless Chrome for JavaScript tests
Capybara.register_driver :selenium_chrome_headless do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('--headless')
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-dev-shm-usage')
  options.add_argument('--disable-gpu')

  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end

Capybara.javascript_driver = :selenium_chrome_headless
# -----------------------------
World(Warden::Test::Helpers)
Warden.test_mode!

After do
  Warden.test_reset!
end

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { except: [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

# Configure database cleaner for JavaScript scenarios
Before('@javascript') do
  DatabaseCleaner.strategy = :truncation
end

After('@javascript') do
  DatabaseCleaner.clean
end

# ============================================
# Restaurant Data Setup for Tests
# ============================================

Before do
  # Seed database for tests if empty
  if Restaurant.count == 0
    puts "Seeding test database with restaurants..."
    load Rails.root.join('db', 'seeds.rb')
    puts "Loaded #{Restaurant.count} restaurants"
  end

  # Initialize restaurant service for all scenarios
  @restaurant_service = RestaurantService.new
end
